// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fddccbdscoasgljujgco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZGNjYmRzY29hc2dsanVqZ2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzk0ODIsImV4cCI6MjA3MDkxNTQ4Mn0.d1GEJnWDJHMf9s5uq2DRzl59sEs7r1LbJ4w4m-35eng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});